name: Hello World

on:
  workflow_dispatch:

  repository_dispatch:
      types: [custom-event]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, World!"
