name: Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        required: true
        default: 'World'

  workflow_call:
    inputs:
      name:
        type: string
        required: true
        default: 'World'

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, ${{ inputs.name }}!" >> $GITHUB_OUTPUT
